In [3]:
import numpy as np

In [5]:
integers = np.arange(1,21)

In [6]:
integers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
even_no=integers[1: : 2]

In [8]:
even_no

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
rand_array=np.random.randint(10,101,(5,4))

In [10]:
rand_array

array([[82, 70, 23, 75],
       [82, 74, 85, 81],
       [60, 78, 68, 93],
       [59, 54, 85, 33],
       [63, 87, 52, 95]], dtype=int32)

In [12]:
rand_array[:3,:2]

array([[82, 70],
       [82, 74],
       [60, 78]], dtype=int32)

In [13]:
integers.resize(4,5)

In [14]:
integers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
integers=integers.flatten()

In [18]:
integers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
rand_array2=np.random.randint(10,101,(4,5))

In [20]:
np.matmul(rand_array,rand_array2)

array([[14087, 18204, 11107, 13943, 12293],
       [15277, 24020, 16421, 18709, 18775],
       [13881, 22623, 14515, 15849, 17018],
       [11019, 17330, 12812, 14469, 14959],
       [14777, 22402, 13759, 15331, 16213]], dtype=int32)

In [29]:
array50=np.random.randint(0,101,(50,))
array50

array([79, 93, 27, 53, 44, 34,  0, 74, 22, 81, 18, 25, 93, 44,  6, 74, 29,
       17, 41, 84, 41, 29, 57, 26, 94, 18, 24, 75, 12, 23, 71, 36, 51, 26,
       36, 69, 93, 10, 12, 20, 87, 43, 23, 71,  7, 89, 29, 35, 13, 27],
      dtype=int32)

In [30]:
array50[array50>50]

array([79, 93, 53, 74, 81, 93, 74, 84, 57, 94, 75, 71, 51, 69, 93, 87, 71,
       89], dtype=int32)

In [31]:
array50[range(2,50,6)]

array([27, 22,  6, 41, 24, 51, 12,  7], dtype=int32)

In [32]:
array50[[1,5,8,27,39,46]]

array([93, 34, 22, 75, 20, 29], dtype=int32)

In [33]:
rand_array

array([[82, 70, 23, 75],
       [82, 74, 85, 81],
       [60, 78, 68, 93],
       [59, 54, 85, 33],
       [63, 87, 52, 95]], dtype=int32)

In [35]:
rand_array.mean(axis=0)

array([69.2, 72.6, 62.6, 75.4])

In [36]:
rand_array.max(axis=0)

array([82, 87, 85, 95], dtype=int32)

In [37]:
rand_array.sum(axis=0)

array([346, 363, 313, 377])